### PR TITLE
fix: pass timeout to request

### LINKED ISSUE #7: Requests to relative URL fail
## Steps to reproduce

1. Perform a `fetch('/login')` request in Node-like environment.
1. See the following error from the `XMLHttpRequest` class:

```
    TypeError: Invalid URL: /login

      2152 |             this.readyState = this.LOADING;
      2153 |             this.data = data || '';
    > 2154 |             const url = new URL(this.url);
           |                         ^
      2155 |             const req = {
      2156 |                 url: cleanUrl(url),
      2157 |                 method: this.method,
```

### PR DESCRIPTION
**Pull request by marcosvega91**
## Changes

- Propagates callbacks (`ontimeout`, `onreadystatechange`, etc.) and event listeners (`timeout`, `error`, etc.) from the captured XHR instance to the original XHR instance.
- Propagates the `timeout` property to the original XHR, so that the request timeout is respected (i.e. when using `axios` with timeout).
- Adds respective tests.

## GitHub

- Originated from https://github.com/mswjs/msw/issues/284
- Fixes #7

Timeout was not passed to original request when no mock response is found.
Hope to did the right thing 😄 

Timeout should be added only if the request is async so when `this.async === true`

### CODE REVIEW

**Comment by kettanaito** [comment]
Could you please resolve the failing tests on CI?

**Comment by marcosvega91** [comment]
Yes I'm looking into it

**Comment by marcosvega91** [comment]
It should be good now 🥳

**Comment by kettanaito** [comment]
Looks good! The test remains. Would you be interested in writing a test case for this `timeout` change?
Basically, that NRI now respects timeout on XMLHttpRequest.

**Comment by marcosvega91** [comment]
I have added the test, I think then that there is also an issue elsewhere not regarding this PR. If you set async for all requests in `xhr` helper, the error ` The "superCtor" argument must be of type function. Received undefinedTypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type function. Received undefined` will thrown. Is the error that kent send on discord some day ago.

**Comment by marcosvega91** [comment]
If is ok for I think that this can be merged and when I'll back I will try to figure out the other problem. What do you think ?

File: test/helpers.ts [hunk 1]
```diff
@@ -183,7 +186,11 @@ export async function xhr(
         )
       })
     }
-
+    req.timeout = options?.timeout ?? 0
+    req.ontimeout = function (event) {
```
Comment (kettanaito) [inline test/helpers.ts:190]: I think we shouldn't extend this utility with the timeout functionality, as it introduces too much complexity into this utility function. 

Instead, we should perform a raw `XMLHttpRequest` and assert the proper timeout handling with both callbacks and events attached to XHR instance. I'll push that test suite right now.

File: test/intercept/XMLHttpRequest/XMLHttpRequest.test.ts [hunk 2]
```diff
@@ -218,3 +218,19 @@ test('intercepts an HTTP PATCH request', async () => {
...
+  try {
+    await xhr('GET', 'http://httpbin.org/get?userId=123', {
+      headers: {
+        'x-custom-header': 'yes',
+      },
+      timeout: 1,
+      onTimeout,
+      async: true,
+    })
+  } catch (error) {
```
Comment (kettanaito) [inline test/intercept/XMLHttpRequest/XMLHttpRequest.test.ts:233]: By extending our `xhr` util, we also make our test behave not like an actual XHR instance would behave. XHR won't throw on timeout, and neither should our test.

File: src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts [hunk 3]
```diff
@@ -325,7 +324,9 @@ export const createXMLHttpRequestOverride = (
             originalRequest.onerror = this.onerror
             originalRequest.ontimeout = this.ontimeout
             originalRequest.onreadystatechange = this.onreadystatechange
-
+            if (this.async) {
+              originalRequest.timeout = this.timeout
```
Comment (kettanaito) [inline src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts:328]: Should we always inherit `.timeout` callback? I feel it's the end user's responsibility to align that they assign `timeout` callback only for `async` XHR.

Comment (marcosvega91) [reply src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts:328]: If we assign a timeout function when a request is not async an error is thrown. We can leave this error for the user

**Comment by kettanaito** [comment]
Please, I will have to force push into your feature branch. Do not push anything new until that's done. Thank you!

**Comment by marcosvega91** [comment]
I can't push until next week so is not a problem. Thank you @kettanaito

File: src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts (hunk 3 above)
Comment (marcosvega91) [reply src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts:328]: We can assign timeout function only if is passed. In this way the error will be thrown if xhr is not used in the right way

**Comment by kettanaito** [comment]
I've reworked the test and ensures that callbacks _and_ event listeners were propagated between XHR instances, since previously if you listed on `timeout` via `req.addEventListener('timeout', handler)` that would not trigger the timeout event, and the test would fail.

The changes are ready to go.
